set nocompatible                " Use Vim defaults instead of 100% vi compatibility
set history=50                  " Keep 50 lines of command line history
set ruler                       " Show the cursor position all the time
let mapleader="\<Space>"        " Set spacebar as a leader key for shortcuts

" Suffixes that get lower priority when doing tab completion for filenames.
" These are files we are not likely to want to edit or read.
set suffixes=.bak,~,.swp,.o,.info,.aux,.log,.dvi,.bbl,.blg,.brf,.cb,.ind,.idx,.ilg,.inx,.out,.toc,.png,.jpg
let g:netrw_dirhistmax=0        " Do not clutter the filesystem with .netwrhist

set number                      " Show line number on the side
set showmatch                   " When a bracket is inserted, briefly jump to the matching one
                                " The jump is done only if the match can be
                                " seen on the screen. The time to show the
                                " match can be set with 'matchtime'

set incsearch                   " Immediatly search, while still typing the pattern
set hlsearch                    " Highlight all search pattern matches
set ignorecase                  " Case-agnostic search
set smartcase                   " Override 'ignorecase' if pattern contains uppercase characters
" Map <C-L> (redraw screen) to also turn off the search highlighting until the
" next search
nnoremap <C-L> :nohl<CR><C-L>

set expandtab                   " Use spaces for indent when TAB is hit
                                " Allows for consistent file layout across
                                " Various OSes
set shiftwidth=4                " Number of spaces to use for each step of (auto)indent
set softtabstop=4               " Number of spaces a TAB key inserts

set autoindent                  " Copy indent from the previous line
filetype plugin indent on       " Enable file-type based indentation
syntax on                       " Syntax highlighting

set textwidth=80                " Maximum row width. A longer line will be broken to fit this
set colorcolumn=+1              " Highlight the column after the textwidth
set mouse=a                     " Enable mouse
set backspace=indent,eol,start  " Allow backspacing over autoindent, line breaks and start of insert action
set wildmenu                    " Command line menu suggestions

" Pathogen init
runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()

" Apply solarized theme
set background=dark
colorscheme solarized
highlight clear SignColumn      " Prevent gutter from becoming ugly gray

" Settings for vim-airline plugin
set laststatus=2                " Show vim-airline (status line) even if there is only one window
set noshowmode                  " Avoid the double mode info display (eg. INSERT)
let g:airline_powerline_fonts=1 " Enable powerline glyphs for better formatting

" Settings for NERDTree
nnoremap <Leader>n :NERDTreeToggle<CR>
" Close vim when the only open window left is NERDTree
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" Settings for YouCompleteMe
" Set the default config file for semantic C-family languages completion
let g:ycm_global_ycm_extra_conf="~/.vim/ycm_default_conf.py"
let g:ycm_complete_in_comments=1            " Use YCM completion in comments
let g:ycm_seed_identifiers_with_syntax=1    " Use language keywords as completions
let g:ycm_key_detailed_diagnostics="<Leader>yd"
" GoTo symbol's declaration/definition:
nnoremap <Leader>yg :YcmCompleter GoTo<CR>
" YCM type recognition utility:
nnoremap <Leader>yt :YcmCompleter GetType<CR>
" Look up the appropriate documentation:
nnoremap <Leader>yo :YcmCompleter GetDoc<CR>
" Automatically fix minor syntax errors
nnoremap <Leader>yf :YcmCompleter FixIt<CR>

" Settings for syntastic
" YCM uses the following settings as well:
let g:syntastic_warning_symbol="w>"         " Clearer warning & error signs
let g:syntastic_error_symbol="e>"
let g:syntastic_always_populate_loc_list=1  " Populate loc_list with error locations
" End of YCM shared section
let g:syntastic_auto_loc_list=1             " Open location list on errors
" Explicit check:
nnoremap <Leader>sc :SyntasticCheck<CR>
